// Reemplaza foto/boceto por tus imágenes reales y los textos por los del docx "HALLOWEEN TEX EXPLICATIU".
// Para añadir una propuesta futura, agrega un objeto más a este array (misma cantidad de zonas).
export const proposals = [
  {
    id: "propuesta-a",
    nombre: "Stranger Things",
    zonas: [
      {
        id: "entrada",
        nombre: "Entrada principal — Stranger Mar",
        nota: "Apertura del portal: fuego, humo y neón rojo.",
        foto: "images/propuesta-a/entrada-foto.jpg",
        boceto: "images/propuesta-a/entrada-boceto.png",
        texto: "Apertura del portal ambientada en negro y rojo con fuego. Primera puerta con 2 personas controlando el acceso, zona de tiquets con 1 persona y zona de compra/venta de entradas con 3 personas.",
      },
      {
        id: "arcada-1",
        nombre: "Arcada 1 - Laboratorio Hawkins",
        nota: "Once experimenta entre alarmas y luces fluorescentes.",
        foto: "images/propuesta-a/arcada-1-foto.jpg",
        boceto: "images/propuesta-a/arcada-1-boceto.png",
        texto: "Laboratorio de Hawkins con Eleven y 4 personajes más. Experimentos entre luces fluorescentes, alarmas, paredes de laboratorio y un zumbido eléctrico de fondo.",
      },
      {
        id: "arcada-2",
        nombre: "Arcada 2 - Laboratorio Hawkins (continuación)",
        nota: "Las alarmas no dejan de sonar.",
        foto: "images/propuesta-a/arcada-2-foto.jpg",
        boceto: "images/propuesta-a/arcada-2-boceto.png",
        texto: "Continúa el laboratorio: más equipo científico, luces de alarma parpadeantes y el zumbido eléctrico que se intensifica al avanzar.",
      },
      {
        id: "arcada-3",
        nombre: "Arcada 3 - Desaparición de Will",
        nota: "Will no ha vuelto a casa...",
        foto: "images/propuesta-a/arcada-3-foto.jpg",
        boceto: "images/propuesta-a/arcada-3-boceto.png",
        texto: "Will no vuelve a casa: su bicicleta queda abandonada en la escena. La madre y el hermano de Will buscan comunicarse desesperadamente con él a través de las luces de Navidad.",
      },
      {
        id: "arcada-4",
        nombre: "Arcada 4 - Desaparición de Will (continuación)",
        nota: "Un demogorgon intenta salir de la pared.",
        foto: "images/propuesta-a/arcada-4-foto.jpg",
        boceto: "images/propuesta-a/arcada-4-boceto.png",
        texto: "La casa de los Byers, desesperada y decorada con luces de Navidad parpadeantes. Al fondo, un demogorgon intenta atravesar la pared.",
      },
      {
        id: "arcada-5",
        nombre: "Arcada 5 - El Demogorgon",
        nota: "El monstruo ha entrado en Hawkins.",
        foto: "images/propuesta-a/arcada-5-foto.jpg",
        boceto: "images/propuesta-a/arcada-5-boceto.png",
        texto: "El monstruo entra en Hawkins: dimensión del Upside Down con paredes orgánicas, raíces y niebla roja. Sonidos de respiración y gritos envuelven el paso.",
      },
      {
        id: "arcada-6",
        nombre: "Arcada 6 - El Demogorgon (continuación)",
        nota: "Algo respira entre la niebla roja.",
        foto: "images/propuesta-a/arcada-6-foto.jpg",
        boceto: "images/propuesta-a/arcada-6-boceto.png",
        texto: "Raíces retorcidas cubren las paredes mientras la niebla roja se espesa; los sonidos de respiración y los gritos se escuchan cada vez más cerca.",
      },
      {
        id: "arcada-7",
        nombre: "Arcada 7 - Starcourt",
        nota: "Starcourt Mall: el escenario de la pesadilla.",
        foto: "images/propuesta-a/arcada-7-foto.jpg",
        boceto: "images/propuesta-a/arcada-7-boceto.png",
        texto: "Starcourt Mall convertido en escenario de pesadilla: un laboratorio soviético con militares y científicos custodia el lugar.",
      },
      {
        id: "arcada-8",
        nombre: "Arcada 8 - Starcourt (continuación)",
        nota: "La colmena de demogorgons espera.",
        foto: "images/propuesta-a/arcada-8-foto.jpg",
        boceto: "images/propuesta-a/arcada-8-boceto.png",
        texto: "Demogorgons y la colmena aparecen entre los pasillos del centro comercial, en el corazón del laboratorio soviético.",
      },
      {
        id: "patio-central",
        nombre: "Patio central - El Cementerio",
        nota: "Max cuelga entre las tumbas...",
        foto: "images/propuesta-a/patio-central-foto.jpg",
        boceto: "images/propuesta-a/patio-central-boceto.png",
        texto: "Se simula la escena de Max colgando en el cementerio: tumbas y un muñeco colgado representando a Max entre las lápidas.",
      },
      {
        id: "tramo-final",
        nombre: "Tramo final - Vecna / Upside Down",
        nota: "El final te espera en el Upside Down.",
        foto: "images/propuesta-a/tramo-final-foto.png",
        boceto: "images/propuesta-a/tramo-final-boceto.png",
        texto: "Tramo final ambientado en Vecna y el Upside Down: el clímax del recorrido antes de volver a la realidad.",
      },
    ],
  },
  {
    id: "propuesta-b",
    nombre: "Aula Magna: Sin Salida",
    video: "images/propuesta-b/video-recorrido.mp4",
    historia:
      "Durante unas obras de mantenimiento rutinarias en el patio del colegio, los operarios derriban por error un muro donde había un conducto clausurado hace cien años. Tras el derrumbe queda al descubierto una zona del edificio olvidada misteriosamente. Un jefe de obra reúne a una comisión de investigación para observar el lugar antes de precintarlo, pero al adentrarse descubren una aterradora verdad: el antiguo colegio jamás se vació, sino que quedó atrapado en un bucle temporal custodiando el antiguo cementerio municipal sobre el que fue edificada la escuela actual.",
    zonas: [
      {
        id: "entrada",
        nombre: "Entrada principal — Recepción",
        nota: "Zona de obra: firma aquí antes de bajar.",
        foto: "images/propuesta-b/entrada-foto.jpg",
        boceto: "images/propuesta-b/entrada-boceto.jpg",
        texto: "Zona de obra con mesas, planos y material de construcción disperso (mangueras, cubos, palets). El guía —un jefe de obra— reúne a un grupo de 8-10 participantes y explica la situación (puede proyectarse un vídeo). Se piden los nombres de algunos visitantes antes de bajar. A mitad de la rampa hacia las arcadas, el capataz advierte: \"Durante las obras rutinarias de mantenimiento del patio hemos roto un muro sellado hace 100 años... no sabemos qué hay detrás y no aparece en los planos...\". Un obrero aterrorizado sale huyendo gritando que no bajen, y al llegar al primer arco, el jefe de obra elige a un participante para derribar el muro sellado.",
      },
      {
        id: "arcada-1",
        nombre: "Arcada 1 - El Aula Magna",
        nota: "¡Llegan tarde a clase!",
        foto: "images/propuesta-b/arcada-1-foto.jpg",
        boceto: "images/propuesta-b/arcada-1-boceto.jpg",
        texto: "Una clase detenida en el tiempo: pupitres alineados forman un pasillo central muy estrecho, pizarra al fondo y campana escolar distorsionada sonando en bucle. Alumnos con aspecto zombie y ropas mugrientas custodian el paso. Una directora de época golpea la mesa con su vara: \"¡Llegan tarde!\". El profesor pasa lista mientras cruzáis el aula — los alumnos susurran \"¡No digas presente!\" y, al nombrar a los primeros y últimos participantes, todos giran la cabeza para mirarlos fijamente.",
      },
      {
        id: "arcada-2",
        nombre: "Arcada 2 - El Laboratorio",
        nota: "El profesor necesita muestras biológicas.",
        foto: "images/propuesta-b/arcada-2-foto.jpg",
        boceto: "images/propuesta-b/arcada-2-boceto.jpg",
        texto: "Luces intermitentes, botes de conserva y tiras de plástico industrial cuelgan del techo entre humo bajo. Un profesor de ciencias, con gafas rotas y bata manchada de verde y rojo, diseca un maniquí sobre la mesa central y exige que le entreguéis a uno de los vuestros para \"muestras biológicas\".",
      },
      {
        id: "arcada-3",
        nombre: "Arcada 3 - El Laboratorio (continuación)",
        nota: "Algo se mueve bajo los pupitres.",
        foto: "images/propuesta-b/arcada-3-foto.jpg",
        boceto: "images/propuesta-b/arcada-3-boceto.jpg",
        texto: "Bajo mesas cubiertas con faldones oscuros se ocultan varios niños; al pasar el grupo, sacan las manos de golpe golpeando las patas metálicas de los pupitres con recipientes de metal, generando un estruendo repentino.",
      },
      {
        id: "arcada-4",
        nombre: "Arcada 4 - El Comedor Infernal",
        nota: "¿Tenéis hambre?",
        foto: "images/propuesta-b/arcada-4-foto.jpg",
        boceto: "images/propuesta-b/arcada-4-boceto.jpg",
        texto: "Mesas corridas bloquean el paso formando un zigzag; el suelo cruje bajo platos de plástico aplastados y flota un olor penetrante a vinagre y especias. Dos cocineros zombis con gorros altos afilan sus machetes de plástico rítmicamente contra bandejas de metal.",
      },
      {
        id: "arcada-5",
        nombre: "Arcada 5 - El Comedor Infernal (continuación)",
        nota: "Hoy comeremos carne fresca.",
        foto: "images/propuesta-b/arcada-5-foto.jpg",
        boceto: "images/propuesta-b/arcada-5-boceto.jpg",
        texto: "Los alumnos hacen fila esperando el rancho de comida. Cuando el cocinero golpea una olla con el cazo metálico, todos giran a la vez con caras desencajadas gritando \"¡Tenemos hambre!\" — \"¿TENÉIS HAMBRE? HOY COMEREMOS CARNE FRESCA.\"",
      },
      {
        id: "arcada-6",
        nombre: "Arcada 6 - La Biblioteca",
        nota: "Shhh... no hagas ruido.",
        foto: "images/propuesta-b/arcada-6-foto.jpg",
        boceto: "images/propuesta-b/arcada-6-boceto.jpg",
        texto: "El ambiente cambia a un silencio inquietante: papeles cuelgan del techo, telarañas y luces flash desconcertantes. La bibliotecaria espectral, sepultada tras montañas de libros de aspecto ancestral, lanza un susurro seco y amplificado en cuanto alguien habla o hace ruido: \"¡¡¡SILENCIO!!!\"",
      },
      {
        id: "arcada-7",
        nombre: "Arcada 7 - La Biblioteca (continuación)",
        nota: "Figuras blancas se ocultan entre las columnas.",
        foto: "images/propuesta-b/arcada-7-foto.jpg",
        boceto: "images/propuesta-b/arcada-7-boceto.jpg",
        texto: "Siete niños con túnicas blancas o grisáceas y máscaras lisas se ocultan tras las columnas del lado del patio, entrando y saliendo silenciosamente entre cortinas de plástico negro, rozando sutilmente a los visitantes sin tocar de forma brusca.",
      },
      {
        id: "patio-central",
        nombre: "Patio central - El Patio de las Almas",
        nota: "El patio esconde un cementerio olvidado.",
        foto: "images/propuesta-b/patio-central-foto.jpg",
        boceto: "images/propuesta-b/patio-central-boceto.jpg",
        texto: "Al huir de la biblioteca creéis estar a salvo en el exterior, pero el patio central se construyó sobre el antiguo camposanto del pueblo, olvidado hace un siglo. Los alumnos y profesores desaparecidos en 1926 nunca huyeron: el colegio se erigió para contener las almas del cementerio, y al derribar el muro en las obras, las tumbas del patio han vuelto a abrirse. Un sendero sinuoso entre lápidas caseras, tumbas abiertas y una cripta central marca el único camino seguro. El Sepulturero, con abrigo viejo, sombrero raído y una pala de hierro real, custodia el lugar: \"NADIE ABANDONA MI CASA. TENGO UN LUGAR PREPARADO PARA USTEDES.\" Zombis de las fosas y espectros errantes (6 a 8 niños) se incorporan y deambulan entre las lápidas mientras cruzáis el laberinto sin despertar al Guardián de las Tumbas.",
      },
      {
        id: "tramo-final",
        nombre: "Tramo final - Los No-Muertos",
        nota: "VOLVERÉIS... no tengo prisa.",
        foto: "images/propuesta-b/tramo-final-foto.png",
        boceto: "images/propuesta-b/tramo-final-boceto.png",
        texto: "Justo antes de cruzar la verja hacia la zona segura, el Sepulturero golpea su pala y advierte entre risas: \"VOLVEREIS, NO TENGO PRISA... ahahahah\". La salida real os lleva hacia el campo de fútbol, donde espera la última sorpresa: el Loco de la Motosierra.",
      },
    ],
  },
  {
    id: "propuesta-c",
    nombre: "Orfanato",
    historia:
      "Idea aún en desarrollo: se trabaja con la sensación de un colegio abandonado donde quedan huellas de infancia y pérdida, sin una escenografía cerrada aún definida para cada tramo.",
    zonas: [
      {
        id: "foto-1",
        nombre: "Referencia visual 1",
        nota: "Imagen de la idea en desarrollo.",
        foto: "images/orfanato/30099b57-97c2-4bae-99e1-23d42f92501a.JPG",
        boceto: "images/orfanato/30099b57-97c2-4bae-99e1-23d42f92501a.JPG",
        texto: "",
      },
      {
        id: "foto-2",
        nombre: "Referencia visual 2",
        nota: "Imagen de la idea en desarrollo.",
        foto: "images/orfanato/69c23b9a-9b9b-4645-89ca-88a8a14ae5a8.JPG",
        boceto: "images/orfanato/69c23b9a-9b9b-4645-89ca-88a8a14ae5a8.JPG",
        texto: "",
      },
    ],
  },
  {
    id: "propuesta-d",
    nombre: "Cualquiera de las anteriores + tramo final: La carpa de la última risa",
    historia:
      "En cualquiera de las propuestas, solo se cambiaría el tramo final: la zona final del recorrido se convertiría en una carpa de aire libre, situada al final del túnel de arcadas, en la parte de arriba. La idea es que la última sorpresa conecte con la parte infantil y con la actividad de manualidades para los peques.",
    zonas: [
      {
        id: "tramo-final",
        nombre: "Tramo final — La carpa de la última risa",
        nota: "Solo cambia la parte final del recorrido.",
        foto: "images/obra/escena-final.png",
        boceto: "images/propuesta-b/tramo-final-boceto.png",
        texto: "La última parte cambiaría para abrir un espacio de aire libre, más teatral y festivo, con un tono casi circense pero algo inquietante. El título sugerido sería: “🎪 La carpa de la última risa”. Esta sección se plantearía como la sorpresa final y la enlazaría con la parte de los niños, que podrían participar con manualidades o con una pequeña ambientación del propio tramo. No hace falta cambiar la entrada ni las arcadas; solo se redefiniría el último tramo como cierre del recorrido.",
      },
    ],
  },
];
