// Reemplaza foto/boceto por tus imágenes reales y los textos por los del docx "HALLOWEEN TEX EXPLICATIU".
// Para añadir una propuesta futura, agrega un objeto más a este array (misma cantidad de zonas).
export const proposals = [
  {
    id: "aula_magna",
    nombre: "Aula Magna",
    video: "images/propuesta-b/video-recorrido.mp4",
    historia:
      "Durante unas obras de mantenimiento rutinarias en el patio del colegio, los operarios derriban por error un muro donde había un conducto clausurado hace cien años. Tras el derrumbe queda al descubierto una zona del edificio olvidada misteriosamente. Un jefe de obra reúne a una comisión de investigación para observar el lugar antes de precintarlo, pero al adentrarse descubren una aterradora verdad: el antiguo colegio jamás se vació, sino que quedó atrapado en un bucle temporal custodiando el antiguo cementerio municipal sobre el que fue edificada la escuela actual.",
    zonas: [
      {
        id: "entrada",
        nombre: "Entrada principal — Recepción",
        nota: "Zona de obra: firma aquí antes de bajar.",
        foto: "images/propuesta-b/entrada-foto.jpg",
        boceto: "images/propuesta-b/entrada-boceto.jpg",
        texto: "Zona de obra con mesas, planos y material de construcción disperso. El guía reúne a un grupo de 8-10 participantes y explica la situación antes de bajar. A mitad de la rampa, el capataz advierte que se ha abierto un muro sellado hace 100 años y que no aparece en los planos. Un obrero aterrorizado sale huyendo gritando que no bajen.",
      },
      {
        id: "arcada-1-3",
        nombre: "Arcada 1-3 — Aula Magna y laboratorio",
        nota: "El aula detenida y el profesor del terror.",
        foto: "images/propuesta-b/arcada-1-foto.jpg",
        boceto: "images/propuesta-b/arcada-1-boceto.jpg",
        texto: "Aula Magna congelada en el tiempo: pupitres alineados, pizarra al fondo y campana escolar en bucle. Una directora de época golpea la mesa con su vara y el profesor exige muestras biológicas mientras un grupo de alumnos zombie observa desde los pupitres.",
      },
      {
        id: "arcada-4-5",
        nombre: "Arcada 4-5 — Comedor infernal",
        nota: "Platos, metal y hambre.",
        foto: "images/propuesta-b/arcada-4-foto.jpg",
        boceto: "images/propuesta-b/arcada-4-boceto.jpg",
        texto: "Mesas corridas forman un zigzag con platos rotos, vinagre y olor a muerte. Dos cocineros zombis golpean bandejas con machetes de plástico y gritan que hoy comerán carne fresca.",
      },
      {
        id: "arcada-6-7",
        nombre: "Arcada 6-7 — Biblioteca y figuras blancas",
        nota: "Silencio, telarañas y susurros.",
        foto: "images/propuesta-b/arcada-6-foto.jpg",
        boceto: "images/propuesta-b/arcada-6-boceto.jpg",
        texto: "La biblioteca cambia a un silencio inquietante con papeles colgando del techo y luces intermitentes. Las figuras blancas entre las columnas se deslizan sin hacer ruido mientras la bibliotecaria espectral lanza un susurro: \"SILENCIO\".",
      },
      {
        id: "patio-central",
        nombre: "Patio central — El patio de las almas",
        nota: "Cementerio oculto bajo el patio.",
        foto: "images/propuesta-b/patio-central-foto.jpg",
        boceto: "images/propuesta-b/patio-central-boceto.jpg",
        texto: "El patio central se construyó sobre un antiguo cementerio del pueblo. Lápidas, tumbas abiertas y un sendero sinuoso acompañan el paso de los alumnos mientras el Sepulturero custodia la entrada y los zombis de las fosas se incorporan.",
      },
      {
        id: "tramo-final",
        nombre: "Tramo final — Los No-Muertos",
        nota: "La salida de la pesadilla.",
        foto: "images/propuesta-b/tramo-final-foto.png",
        boceto: "images/propuesta-b/tramo-final-boceto.png",
        texto: "Justo antes de cruzar la verja, el Sepulturero advierte con risas que volverán. La salida real conduce al campo de fútbol, donde espera la última sorpresa: el Loco de la Motosierra.",
      },
    ],
  },
  {
    id: "stranger_things",
    nombre: "Stranger Things",
    zonas: [
      {
        id: "entrada",
        nombre: "Entrada principal — Stranger Mar",
        nota: "Apertura del portal: fuego, humo y neón rojo.",
        foto: "images/propuesta-a/entrada-foto.jpg",
        boceto: "images/propuesta-a/entrada-boceto.png",
        texto: "Apertura del portal ambientada en negro y rojo con fuego. Primera puerta con 2 personas controlando el acceso, zona de tiquets con 1 persona y zona de compra/venta de entradas con 3 personas.",
      },
      {
        id: "arcada-2-3",
        nombre: "Arcada tramo 2-3 — Hawkins Lab / Desaparición de Will",
        nota: "Eleven, experimentos, Will y la casa de Lois.",
        foto: "images/propuesta-a/arcada-1-foto.jpg",
        boceto: "images/propuesta-a/arcada-1-boceto.png",
        texto: "Hawkins Lab: Eleven acompaña a 4 personas más en una escena de experimentos y alarmas. Luces fluorescentes, alarmas, paredes de laboratorio, sonido eléctrico y una atmósfera que convierte la ciencia en terror puro. Poco después, Will no vuelve a casa. Su bicicleta queda abandonada y la casa de Lois se convierte en un escenario de desesperación mientras buscan a su hijo con luces de Navidad iluminando la noche. La pared se abre y el demogorgon intenta salir de la dimensión del Upside Down.",
      },
      {
        id: "arcada-4-5",
        nombre: "Arcada tramo 4-5 — El Demogorgon / Starcourt",
        nota: "La criatura entra en Hawkins y el horror se expande.",
        foto: "images/propuesta-a/arcada-2-foto.jpg",
        boceto: "images/propuesta-a/arcada-2-boceto.png",
        texto: "El monstruo entra en Hawkins. La dimensión del Upside Down se abre con demogorgones, paredes orgánicas, raíces, niebla, luces rojas y sonidos de respiración y gritos que anuncian la invasión del terror. Después, Starcourt Mall se convierte en el escenario del infierno: un laboratorio soviético con militares y científicos, demogorgones y una colmena que transforman el centro comercial en un laberinto de miedo, caos y destrucción total.",
      },
      {
        id: "patio-central",
        nombre: "Patio central — Cementerio",
        nota: "Max colgando entre tumbas.",
        foto: "images/propuesta-a/patio-central-foto.jpg",
        boceto: "images/propuesta-a/patio-central-boceto.png",
        texto: "Escena del cementerio: Max cuelga entre tumbas mientras aparece una silueta que simula su figura. Hay lápidas, tierra, niebla y una atmósfera funeraria que refuerza la tragedia y la presencia sobrenatural.",
      },
      {
        id: "tramo-final",
        nombre: "Tramo final — Vecna / Upside Down",
        nota: "Patio superior, árboles rojos y nubes colgantes.",
        foto: "images/propuesta-a/tramo-final-foto.png",
        boceto: "images/propuesta-a/tramo-final-boceto.png",
        texto: "Patio superior con Vecna como figura central. Árboles con luces rojas, nubes colgantes y una atmósfera infernal. Cartón negro simula grietas en el suelo y más demogorgones rodean la última escena del clímax.",
      },
    ],
  },
  {
    id: "orfanato",
    nombre: "Orfanato",
    historia:
      "Idea aún en desarrollo: se trabaja con la sensación de un colegio abandonado donde quedan huellas de infancia y pérdida, sin una escenografía cerrada aún definida para cada tramo.",
    zonas: [
      {
        id: "foto-1",
        nombre: "Referencia visual 1",
        nota: "Imagen de la idea en desarrollo.",
        foto: "images/orfanato/30099b57-97c2-4bae-99e1-23d42f92501a.JPG",
        boceto: "images/orfanato/30099b57-97c2-4bae-99e1-23d42f92501a.JPG",
        texto: "",
      },
      {
        id: "foto-2",
        nombre: "Referencia visual 2",
        nota: "Imagen de la idea en desarrollo.",
        foto: "images/orfanato/69c23b9a-9b9b-4645-89ca-88a8a14ae5a8.JPG",
        boceto: "images/orfanato/69c23b9a-9b9b-4645-89ca-88a8a14ae5a8.JPG",
        texto: "",
      },
    ],
  },
  {
    id: "cosecha",
    nombre: "Cosecha",
    video: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
    historia:
      "Es 2026 y la vida ha transcurrido tranquila en Vilassar de Mar, hasta ahora. Desde mediados de septiembre han empezado a producirse desapariciones. Todas tienen un elemento en común: son niños y niñas de 11 años, nacidos en 2015. Los niños se acuestan una noche y a la mañana siguiente ya no están. La noticia llega a todos los rincones del mundo y lejos, muy lejos, en los pueblos andinos, una mujer muy anciana se estremece al recordar: 'No puede ser, ¡está volviendo a suceder!'.",
    zonas: [
      {
        id: "mensaje-anciana",
        nombre: "La voz del pueblo andino",
        nota: "Una advertencia de hace 100 años.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "Una anciana manda un mensaje a las autoridades de Vilassar de Mar: 'No puede ser, ¡está volviendo a suceder!'. Cuenta que, cuando era pequeña, sus abuelos le hablaron de un suceso del 31 de octubre de 1926, cuando un grupo de niños fueron atraídos por una piedra negra suspendida en el aire y se dirigieron hacia un edificio abandonado en medio de un maizal. Los niños parecían hechizados: 'Cada 100 años empieza…11 años han de tener para las almas poseer…Ayuda…31.10'.",
      },
      {
        id: "maizal",
        nombre: "El maizal de la piedra",
        nota: "La tierra devuelve el poder.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "El maizal es el lugar donde reencarna el poder. Bajo el hechizo, los niños desaparecen y la piedra se alimenta de las almas de quienes tienen 11 años. Los guardianes adultos quedan atrapados y se convierten en criaturas conocidas como Malakruks. La tragedia se repite cada cien años cuando la frontera entre la infancia y la adolescencia es más débil.",
      },
      {
        id: "edificio-abandonado",
        nombre: "Edificio abandonado",
        nota: "Atrapados entre la infancia y el miedo.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "Los niños se dirigen a un edificio abandonado junto al maizal. Las cámaras de seguridad de una fábrica cercana captan a una niña con paso hipnótico acercándose al lugar. Una presencia superior parece estar guiándoles, sin que puedan escapar del atractivo de la piedra negra.",
      },
      {
        id: "guardians",
        nombre: "Los Malakruks",
        nota: "Monstruos que guardan la piedra.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "Los adultos que se adentraron al maizal para intentar rescatar a los niños no volvieron. Quedaron atrapados bajo el hechizo y se transformaron en criaturas guardianas: los Malakruks. Protegen la piedra y dan rienda suelta al terror para que el ritual continúe. Solo romper el poder de la roca puede detener la siguiente Cosecha.",
      },
      {
        id: "cosecha-2026",
        nombre: "La Cosecha de 2015",
        nota: "El 2026 vuelve la desgracia.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "Este año, la desgracia ha caído sobre los nacidos en 2015. Los niños siguen desapareciendo y la maldición reabre sus puertas. La anciana sabe que la piedra necesita una nueva Cosecha y que, si no la destruyen, volverá una vez más. La pregunta sigue en el aire: ¿serán capaces los habitantes de Vilassar de Mar de romper la maldición?",
      },
    ],
  },
  {
    id: "sala-colectiva",
    nombre: "Cada sala, una historia",
    historia:
      "En lugar de dejar una sola carpa final, imaginamos una gran sala colectiva donde cada grupo aporta su propia identidad: obras, colegio, Stranger Things, matadero, niños del maíz, payasos y cualquier otra inspiración que haya surgido. La entrada abre el recorrido, la zona infantil conecta con la imaginación y las arcadas se convierten en pequeñas salas temáticas donde cada propuesta toma su forma y presencia dentro del túnel.",
    zonas: [
      {
        id: "entrada",
        nombre: "Sala 1 — Entrada / umbral del terror",
        nota: "Todos los caminos comienzan aquí.",
        foto: "images/obra/escena-final.png",
        boceto: "images/obra/escena-final.png",
        texto: "La entrada funciona como el gran umbral del miedo: un espacio oscuro, teatral y cargado de tensión que da la bienvenida a quienes se adentran en la experiencia. Aquí se prepara al público para lo que vendrá: una noche donde cada ambiente se revela como una historia distinta, pero con la misma energía inquietante.",
      },
      {
        id: "zona-infantil",
        nombre: "Sala 2 — Zona infantil / imaginación",
        nota: "Una pausa creativa antes del terror.",
        foto: "images/obra/escena-final.png",
        boceto: "images/obra/escena-final.png",
        texto: "Antes del terror, llega la parte más creativa. En esta zona los pequeños pueden participar de manera lúdica, con manualidades, materiales de juego y una estética que conecta la fantasía con la inquietud. Es un momento de pausa, pero también una puerta a la imaginación que encaja con todo lo que vive el visitante después.",
      },
      {
        id: "sala-obras",
        nombre: "Sala 3 — Obras / colegio en ruinas",
        nota: "Entre el ruido, la historia y lo que quedó enterrado.",
        foto: "images/obra/escena-final.png",
        boceto: "images/obra/escena-final.png",
        texto: "Una sala pensada para el misterio de la construcción, los pasillos abandonados, los restos del pasado y la sensación de que algo aún vive bajo el suelo. La historia del colegio, los trabajos de mantenimiento, los suelos contaminados y las ruinas se convierten en una experiencia distinta dentro del mismo túnel.",
      },
      {
        id: "sala-stranger",
        nombre: "Sala 4 — Stranger Things",
        nota: "Ciencia, demogorgones y dimensión oculta.",
        foto: "images/propuesta-a/arcada-2-foto.jpg",
        boceto: "images/propuesta-a/arcada-2-boceto.png",
        texto: "Hawkins, el Upside Down y el horror que se infiltra en lo cotidiano. Aquí se mezclan experimentos, luz fluorescente, alarmas, demogorgones y la sensación de que la realidad se rompe justo delante de tus ojos.",
      },
      {
        id: "sala-matadero",
        nombre: "Sala 5 — Matadero / bestia",
        nota: "Rituales, sangre, muerte y supervivencia.",
        foto: "images/propuesta-a/arcada-2-foto.jpg",
        boceto: "images/propuesta-a/arcada-2-boceto.png",
        texto: "Un entorno cruel, visceral y brutal donde la violencia y el miedo toman forma. El matadero, la sangre, la pesadilla ritual y la sensación de estar atrapado en una historia sin salida dan fuerza a esta sala temática.",
      },
      {
        id: "sala-maiz",
        nombre: "Sala 6 — Niños del maíz",
        nota: "El campo se alimenta de lo que nadie ve.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "La tierra, el maíz y la maldición se fusionan en una sala obsesiva y aterradora. Aquí la historia se convierte en un ritual antiguo, en una vida atrapada entre la infancia, el miedo y la promesa de una cosecha que vuelve cada cien años.",
      },
      {
        id: "sala-payasos",
        nombre: "Sala 7 — Payasos / locura",
        nota: "La risa como arma.",
        foto: "images/propuesta-a/arcada-2-foto.jpg",
        boceto: "images/propuesta-a/arcada-2-boceto.png",
        texto: "La risa es la primera señal de alarma. Payasos, máscaras, visceras de la infancia y una estética casi circense se vuelven aterradoras cuando la locura toma el control y la alegría se transforma en amenaza.",
      },
    ],
  },
];
