// Reemplaza foto/boceto por tus imágenes reales y los textos por los del docx "HALLOWEEN TEX EXPLICATIU".
// Para añadir una propuesta futura, agrega un objeto más a este array (misma cantidad de zonas).
export const proposals = [
  {
    id: "propuesta-b",
    nombre: "Aula Magna: Sin Salida",
    video: "images/propuesta-b/video-recorrido.mp4",
    historia:
      "Durante unas obras de mantenimiento rutinarias en el patio del colegio, los operarios derriban por error un muro donde había un conducto clausurado hace cien años. Tras el derrumbe queda al descubierto una zona del edificio olvidada misteriosamente. Un jefe de obra reúne a una comisión de investigación para observar el lugar antes de precintarlo, pero al adentrarse descubren una aterradora verdad: el antiguo colegio jamás se vació, sino que quedó atrapado en un bucle temporal custodiando el antiguo cementerio municipal sobre el que fue edificada la escuela actual.",
    zonas: [
      {
        id: "entrada",
        nombre: "Entrada principal — Recepción",
        nota: "Zona de obra: firma aquí antes de bajar.",
        foto: "images/propuesta-b/entrada-foto.jpg",
        boceto: "images/propuesta-b/entrada-boceto.jpg",
        texto: "Zona de obra con mesas, planos y material de construcción disperso. El guía reúne a un grupo de 8-10 participantes y explica la situación antes de bajar. A mitad de la rampa, el capataz advierte que se ha abierto un muro sellado hace 100 años y que no aparece en los planos. Un obrero aterrorizado sale huyendo gritando que no bajen.",
      },
      {
        id: "arcada-1-3",
        nombre: "Arcada 1-3 — Aula Magna y laboratorio",
        nota: "El aula detenida y el profesor del terror.",
        foto: "images/propuesta-b/arcada-1-foto.jpg",
        boceto: "images/propuesta-b/arcada-1-boceto.jpg",
        texto: "Aula Magna congelada en el tiempo: pupitres alineados, pizarra al fondo y campana escolar en bucle. Una directora de época golpea la mesa con su vara y el profesor exige muestras biológicas mientras un grupo de alumnos zombie observa desde los pupitres.",
      },
      {
        id: "arcada-4-5",
        nombre: "Arcada 4-5 — Comedor infernal",
        nota: "Platos, metal y hambre.",
        foto: "images/propuesta-b/arcada-4-foto.jpg",
        boceto: "images/propuesta-b/arcada-4-boceto.jpg",
        texto: "Mesas corridas forman un zigzag con platos rotos, vinagre y olor a muerte. Dos cocineros zombis golpean bandejas con machetes de plástico y gritan que hoy comerán carne fresca.",
      },
      {
        id: "arcada-6-7",
        nombre: "Arcada 6-7 — Biblioteca y figuras blancas",
        nota: "Silencio, telarañas y susurros.",
        foto: "images/propuesta-b/arcada-6-foto.jpg",
        boceto: "images/propuesta-b/arcada-6-boceto.jpg",
        texto: "La biblioteca cambia a un silencio inquietante con papeles colgando del techo y luces intermitentes. Las figuras blancas entre las columnas se deslizan sin hacer ruido mientras la bibliotecaria espectral lanza un susurro: \"SILENCIO\".",
      },
      {
        id: "patio-central",
        nombre: "Patio central — El patio de las almas",
        nota: "Cementerio oculto bajo el patio.",
        foto: "images/propuesta-b/patio-central-foto.jpg",
        boceto: "images/propuesta-b/patio-central-boceto.jpg",
        texto: "El patio central se construyó sobre un antiguo cementerio del pueblo. Lápidas, tumbas abiertas y un sendero sinuoso acompañan el paso de los alumnos mientras el Sepulturero custodia la entrada y los zombis de las fosas se incorporan.",
      },
      {
        id: "tramo-final",
        nombre: "Tramo final — Los No-Muertos",
        nota: "La salida de la pesadilla.",
        foto: "images/propuesta-b/tramo-final-foto.png",
        boceto: "images/propuesta-b/tramo-final-boceto.png",
        texto: "Justo antes de cruzar la verja, el Sepulturero advierte con risas que volverán. La salida real conduce al campo de fútbol, donde espera la última sorpresa: el Loco de la Motosierra.",
      },
    ],
  },
  {
    id: "propuesta-a",
    nombre: "Stranger Things",
    zonas: [
      {
        id: "entrada",
        nombre: "Entrada principal — Stranger Mar",
        nota: "Apertura del portal: fuego, humo y neón rojo.",
        foto: "images/propuesta-a/entrada-foto.jpg",
        boceto: "images/propuesta-a/entrada-boceto.png",
        texto: "Apertura del portal ambientada en negro y rojo con fuego. Primera puerta con 2 personas controlando el acceso, zona de tiquets con 1 persona y zona de compra/venta de entradas con 3 personas.",
      },
      {
        id: "arcada-1-2",
        nombre: "Arcada 1-2 — Hawkins Lab",
        nota: "Experimentos, alarmas y Eleven.",
        foto: "images/propuesta-a/arcada-1-foto.jpg",
        boceto: "images/propuesta-a/arcada-1-boceto.png",
        texto: "Laboratori de Hawkins: Eleven acompanya a 4 persones més en una escena de experiments i alarmes. Llum fluorescente, parets de laboratori, so elèctric i un ambient que combina la ciència i el terror.",
      },
      {
        id: "arcada-3-4",
        nombre: "Arcada 3-4 — Will / Demogorgon",
        nota: "Desaparición, casa de Lois y monstruo.",
        foto: "images/propuesta-a/arcada-4-foto.jpg",
        boceto: "images/propuesta-a/arcada-4-boceto.png",
        texto: "Will no torna a casa i la seva bicicleta queda abandonada. La casa de Lois es converteix en un escenari de desesperació amb llums de Nadal, mentre la paret s’obre i el demogorgon intenta sortir de la dimensió del Upside Down.",
      },
      {
        id: "arcada-5-6",
        nombre: "Arcada 5-6 — Starcourt Mall",
        nota: "Laboratorio soviètic, militars, colmena y demogorgons.",
        foto: "images/propuesta-a/arcada-5-foto.jpg",
        boceto: "images/propuesta-a/arcada-5-boceto.png",
        texto: "Starcourt Mall es l’escenari del malson: un laboratori soviètic amb militars i científics, demogorgons i una colmena que converteix el centre comercial en un laberint de por i caos.",
      },
      {
        id: "patio-central",
        nombre: "Patio central — Cementiri",
        nota: "Max penjant entre tombes.",
        foto: "images/propuesta-a/patio-central-foto.jpg",
        boceto: "images/propuesta-a/patio-central-boceto.png",
        texto: "Escena del cementiri: Max penja entre tombes amb un ninot o silueta simulant la seva figura. Un ambient fosc i inquietant que reforça la sensació de tragèdia i de presència sobrenatural.",
      },
      {
        id: "tramo-final",
        nombre: "Tramo final — Vecna / Upside Down",
        nota: "Pati superior, arbres vermells i núvols penjants.",
        foto: "images/propuesta-a/tramo-final-foto.png",
        boceto: "images/propuesta-a/tramo-final-boceto.png",
        texto: "Pati superior amb Vecna com a figura central. Arbres amb llums vermelles, núvols penjants, esquerdes al terra amb cartró negre i més demogorgons envoltant la última escena del clímax.",
      },
    ],
  },
  {
    id: "propuesta-c",
    nombre: "Orfanato",
    historia:
      "Idea aún en desarrollo: se trabaja con la sensación de un colegio abandonado donde quedan huellas de infancia y pérdida, sin una escenografía cerrada aún definida para cada tramo.",
    zonas: [
      {
        id: "foto-1",
        nombre: "Referencia visual 1",
        nota: "Imagen de la idea en desarrollo.",
        foto: "images/orfanato/30099b57-97c2-4bae-99e1-23d42f92501a.JPG",
        boceto: "images/orfanato/30099b57-97c2-4bae-99e1-23d42f92501a.JPG",
        texto: "",
      },
      {
        id: "foto-2",
        nombre: "Referencia visual 2",
        nota: "Imagen de la idea en desarrollo.",
        foto: "images/orfanato/69c23b9a-9b9b-4645-89ca-88a8a14ae5a8.JPG",
        boceto: "images/orfanato/69c23b9a-9b9b-4645-89ca-88a8a14ae5a8.JPG",
        texto: "",
      },
    ],
  },
  {
    id: "cosecha-2015",
    nombre: "La Cosecha de 2015",
    video: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
    historia:
      "Es 2026 y la vida ha transcurrido tranquila en Vilassar de Mar, hasta ahora. Desde mediados de septiembre han empezado a producirse desapariciones. Todas tienen un elemento en común: son niños y niñas de 11 años, nacidos en 2015. Los niños se acuestan una noche y a la mañana siguiente ya no están. La noticia llega a todos los rincones del mundo y lejos, muy lejos, en los pueblos andinos, una mujer muy anciana se estremece al recordar: 'No puede ser, ¡está volviendo a suceder!'.",
    zonas: [
      {
        id: "mensaje-anciana",
        nombre: "La voz del pueblo andino",
        nota: "Una advertencia de hace 100 años.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "Una anciana manda un mensaje a las autoridades de Vilassar de Mar: 'No puede ser, ¡está volviendo a suceder!'. Cuenta que, cuando era pequeña, sus abuelos le hablaron de un suceso del 31 de octubre de 1926, cuando un grupo de niños fueron atraídos por una piedra negra suspendida en el aire y se dirigieron hacia un edificio abandonado en medio de un maizal. Los niños parecían hechizados: 'Cada 100 años empieza…11 años han de tener para las almas poseer…Ayuda…31.10'.",
      },
      {
        id: "maizal",
        nombre: "El maizal de la piedra",
        nota: "La tierra devuelve el poder.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "El maizal es el lugar donde reencarna el poder. Bajo el hechizo, los niños desaparecen y la piedra se alimenta de las almas de quienes tienen 11 años. Los guardianes adultos quedan atrapados y se convierten en criaturas conocidas como Malakruks. La tragedia se repite cada cien años cuando la frontera entre la infancia y la adolescencia es más débil.",
      },
      {
        id: "edificio-abandonado",
        nombre: "Edificio abandonado",
        nota: "Atrapados entre la infancia y el miedo.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "Los niños se dirigen a un edificio abandonado junto al maizal. Las cámaras de seguridad de una fábrica cercana captan a una niña con paso hipnótico acercándose al lugar. Una presencia superior parece estar guiándoles, sin que puedan escapar del atractivo de la piedra negra.",
      },
      {
        id: "guardians",
        nombre: "Los Malakruks",
        nota: "Monstruos que guardan la piedra.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "Los adultos que se adentraron al maizal para intentar rescatar a los niños no volvieron. Quedaron atrapados bajo el hechizo y se transformaron en criaturas guardianas: los Malakruks. Protegen la piedra y dan rienda suelta al terror para que el ritual continúe. Solo romper el poder de la roca puede detener la siguiente Cosecha.",
      },
      {
        id: "cosecha-2026",
        nombre: "La Cosecha de 2015",
        nota: "El 2026 vuelve la desgracia.",
        foto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        boceto: "images/cosecha/46ce9665-fed5-45d8-b241-e58345a4c23d.MP4",
        texto: "Este año, la desgracia ha caído sobre los nacidos en 2015. Los niños siguen desapareciendo y la maldición reabre sus puertas. La anciana sabe que la piedra necesita una nueva Cosecha y que, si no la destruyen, volverá una vez más. La pregunta sigue en el aire: ¿serán capaces los habitantes de Vilassar de Mar de romper la maldición?",
      },
    ],
  },
  {
    id: "propuesta-d",
    nombre: "Cualquiera de las anteriores + tramo final: La carpa de la última risa",
    historia:
      "En cualquiera de las propuestas, solo se cambiaría el tramo final: la zona final del recorrido se convertiría en una carpa de aire libre, situada al final del túnel de arcadas, en la parte de arriba. La idea es que la última sorpresa conecte con la parte infantil y con la actividad de manualidades para los peques.",
    zonas: [
      {
        id: "tramo-final",
        nombre: "Tramo final — La carpa de la última risa",
        nota: "Solo cambia la parte final del recorrido.",
        foto: "images/obra/escena-final.png",
        boceto: "images/propuesta-b/tramo-final-boceto.png",
        texto: "La última parte cambiaría para abrir un espacio de aire libre, más teatral y festivo, con un tono casi circense pero algo inquietante. El título sugerido sería: “🎪 La carpa de la última risa”. Esta sección se plantearía como la sorpresa final y la enlazaría con la parte de los niños, que podrían participar con manualidades o con una pequeña ambientación del propio tramo. No hace falta cambiar la entrada ni las arcadas; solo se redefiniría el último tramo como cierre del recorrido.",
      },
    ],
  },
];
